force-app/main/default/objects/MD_Quote__c/MD_Quote__c.object-meta.xml
<CustomObject>
    <label>Client Proposal</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Client Proposal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Client Proposal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuotePDFGeneratorControllerTest.cls
@isTest
public class QuotePDFGeneratorControllerTest {
  @isTest
  static void testControllerConstructor() {
    MD_Quote__c quote = new MD_Quote__c(Quote_Name__c = 'Test Quote');
    insert quote;
    Test.startTest();
    ApexPages.StandardController sc = new ApexPages.StandardController(quote);
    new QuotePDFGeneratorController(sc);
    Test.stopTest();
    // No assertion needed, just ensure no exceptions and code is covered
  }
}