force-app/main/default/objects/MD_Lead__c/MD_Lead__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MD_Lead__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MD_Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Customer Event</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Google AdWords</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MD_Lead__c/fields/Web_to_Lead__c.field-meta.xml
<CustomField>
    <fullName>Web_to_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Web to Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomWebToLeadHandler.cls
@RestResource(urlMapping='/CustomWebToLead')
global without sharing class CustomWebToLeadHandler {

    global class LeadRequest {
        public String firstName;
        public String lastName;
        public String company;
        public String email;
        public String mobile;
        public Boolean webToLead;
        public String leadSource;
    }

    @HttpPost
    global static void createMDLead() {
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();
        
        LeadRequest request = (LeadRequest) JSON.deserialize(requestBody, LeadRequest.class);

        System.debug('### Email: ' + request.email);
        System.debug('### First Name: ' + request.firstName);
        System.debug('### Last Name: ' + request.lastName);

        MD_Lead__c newLead = new MD_Lead__c(
            First_Name__c = request.firstName,
            Name = request.lastName,
            Company__c = request.company,
            Email__c = request.email,
            Mobile__c = request.mobile,
            Web_to_Lead__c = request.webToLead != null ? request.webToLead : true,
            Lead_Source__c = String.isNotBlank(request.leadSource) ? request.leadSource : 'Website'
        );

        insert newLead;
        
        System.debug('### Lead created successfully with Id: ' + newLead.Id);
    }
}