force-app/main/default/objects/MD_Case__c/MD_Case__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Case__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name (Where Machine Installed)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/City1__c.field-meta.xml
<CustomField>
    <fullName>City1__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>city</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Case Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/Resolution_Description__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Description__c</fullName>
    <label>Case Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Assignment &amp; Routing</fullName>
                <isActive>false</isActive>
                <label>Assignment &amp; Routing</label>
            </value>
            <value>
                <fullName>Closure</fullName>
                <isActive>false</isActive>
                <label>Closure</label>
            </value>
            <value>
                <fullName>Engineer Working</fullName>
                <isActive>false</isActive>
                <label>Engineer Working</label>
            </value>
            <value>
                <fullName>Initiate</fullName>
                <isActive>false</isActive>
                <label>Initiate</label>
            </value>
            <value>
                <fullName>Internal Case Logging</fullName>
                <isActive>false</isActive>
                <label>Internal Case Logging</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
                <isActive>false</isActive>
                <label>Pending Closure</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
                <isActive>false</isActive>
                <label>Resolved</label>
            </value>
            <value>
                <fullName>Tracking &amp; Repair</fullName>
                <isActive>false</isActive>
                <label>Tracking &amp; Repair</label>
            </value>
            <value>
                <fullName>Visits Before Installation</fullName>
                <isActive>false</isActive>
                <label>Visits Before Installation</label>
            </value>
            <value>
                <fullName>Visits For Installation</fullName>
                <isActive>false</isActive>
                <label>Visits For Installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/SuppliedEmail__c.field-meta.xml
<CustomField>
    <fullName>SuppliedEmail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/SuppliedName__c.field-meta.xml
<CustomField>
    <fullName>SuppliedName__c</fullName>
    <label>Web Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/fields/SuppliedPhone__c.field-meta.xml
<CustomField>
    <fullName>SuppliedPhone__c</fullName>
    <label>Web Phone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MD_Case__c/recordTypes/Customer_Complaint.recordType-meta.xml
<RecordType>
    <fullName>Customer_Complaint</fullName>
    <active>true</active>
    <label>Customer Complaint</label>
</RecordType>

force-app/main/default/classes/CustomWebToCaseHandler.cls
@RestResource(urlMapping='/CustomWebToCase')
global without sharing class CustomWebToCaseHandler {

    global class CaseRequest {
        public String suppliedName;
        public String suppliedEmail;
        public String suppliedPhone;
        public String subject;
        public String resolutionDescription;
        public String city;
    }

    @HttpPost
    global static void createMDCase() {
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();
        
        CaseRequest request = (CaseRequest) JSON.deserialize(requestBody, CaseRequest.class);

        System.debug('### suppliedEmail: ' + request.suppliedEmail);
            Id caseRtId = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'MD_Case__c'
            AND DeveloperName = 'Customer_Complaint'
            LIMIT 1
            ].Id;


        MD_Case__c newCase = new MD_Case__c(
            SuppliedName__c = request.suppliedName,
            SuppliedEmail__c = request.suppliedEmail,
            SuppliedPhone__c = request.suppliedPhone,
            Subject__c = request.subject,
            Resolution_Description__c = request.resolutionDescription,
            RecordTypeId = caseRtId,
            Status__c = 'New',
            //Service_Manager__c = '005BK000008W1AHYA0',
            Origin__c = 'Web',
            City1__c = request.city

        );

        if (String.isNotBlank(request.suppliedEmail)) {
            List<Contact> contacts = [SELECT Id, AccountId FROM Contact WHERE Email = :request.suppliedEmail LIMIT 1];
            System.debug('### Contacts found: ' + contacts.size());

            if (!contacts.isEmpty()) {
                Contact matchedContact = contacts[0];
                newCase.ContactId__c = matchedContact.Id;
                System.debug('### matchedContact.Id: ' + matchedContact.Id);

                if (matchedContact.AccountId != null) {
                    newCase.AccountId__c = matchedContact.AccountId;
                    System.debug('### matchedAccount.Id: ' + matchedContact.AccountId);
                } else {
                    System.debug('### Contact found but AccountId is null.');
                }
            } else {
                System.debug('### No contact found matching email.');
            }
        } else {
            System.debug('### Supplied email blank hai.');
        }

        insert newCase;
    }
}