force-app/main/default/objects/Customer_Demand__c/Customer_Demand__c.object-meta.xml
<CustomObject>
    <label>Customer Demand</label>
    <nameField>
        <displayFormat>CDN-{000000000}</displayFormat>
        <label>Customer Demand Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Demands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Demand_Line_item__c/Customer_Demand_Line_item__c.object-meta.xml
<CustomObject>
    <label>Customer Demand Line item</label>
    <nameField>
        <displayFormat>CDLI-{000000000}</displayFormat>
        <label>Customer Demand Line item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Demand Line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Demand_Line_item__c/fields/Customer_Demand__c.field-meta.xml
<CustomField>
    <fullName>Customer_Demand__c</fullName>
    <label>Customer Demand</label>
    <referenceTo>Customer_Demand__c</referenceTo>
    <relationshipLabel>Customer Demand Line items</relationshipLabel>
    <relationshipName>Customer_Demand_Line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Demand_Line_item__c/fields/Material_Master__c.field-meta.xml
<CustomField>
    <fullName>Material_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Master</label>
    <referenceTo>MD_Product2__c</referenceTo>
    <relationshipLabel>Customer Demand Line items</relationshipLabel>
    <relationshipName>Customer_Demand_Line_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Opportunity__c/MD_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Business Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Opportunity__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MD_OpportunityLineItem__c/MD_OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Proposed Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>MD_Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_OpportunityLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>MD_Product2__c</referenceTo>
    <relationshipName>Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_OpportunityLineItem__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MD_Order__c/MD_Order__c.object-meta.xml
<CustomObject>
    <label>Customer Order</label>
    <nameField>
        <displayFormat>CON-{000000000}</displayFormat>
        <label>Customer Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Order__c/fields/Customer_Demand__c.field-meta.xml
<CustomField>
    <fullName>Customer_Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Demand</label>
    <referenceTo>Customer_Demand__c</referenceTo>
    <relationshipName>Customer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_OrderItem__c/MD_OrderItem__c.object-meta.xml
<CustomObject>
    <label>Customer Order Item</label>
    <nameField>
        <displayFormat>COI-{0000000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_OrderItem__c/fields/Customer_Demand_Line_item__c.field-meta.xml
<CustomField>
    <fullName>Customer_Demand_Line_item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Demand Line item</label>
    <referenceTo>Customer_Demand_Line_item__c</referenceTo>
    <relationshipName>Customer_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>Customer Order</label>
    <referenceTo>MD_Order__c</referenceTo>
    <relationshipName>CustmerOrderItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MD_OrderItem__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Master</label>
    <referenceTo>MD_Product2__c</referenceTo>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Quote__c/MD_Quote__c.object-meta.xml
<CustomObject>
    <label>Client Proposal</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Client Proposal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Quote__c/fields/MD_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>MD_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Opportunity</label>
    <referenceTo>MD_Opportunity__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Quote_Line_Item__c/MD_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Client Proposal Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Quote_Line_Item__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>MD_Product2__c</referenceTo>
    <relationshipLabel>Client Proposal Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MD_Quote_Line_Item__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Client Proposal</label>
    <referenceTo>MD_Quote__c</referenceTo>
    <relationshipLabel>Client Proposal Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MDOpportunityLineItemController.cls
public with sharing class MDOpportunityLineItemController {
  @AuraEnabled
  public static String saveSelectedProducts(
    Id varRecId,
    List<Object> selectedProducts,
    String objName
  ) {
    System.debug('varRecId: ' + varRecId);
    System.debug('objName: ' + objName);
    if (String.isBlank(objName)) {
      return 'Error: Parent record (rec) is null. Please ensure the record is loaded before saving.';
    }
    if (objName == 'MD_Opportunity__c') {
      return saveOpportunityLineItems(varRecId, selectedProducts);
    } else if (objName == 'MD_Quote__c') {
      return saveQuoteLineItems(varRecId, selectedProducts);
    } else if (objName == 'MD_Order__c') {
      return saveOrderLineItems(varRecId, selectedProducts);
    } else if (objName == 'Customer_Demand__c') {
      return saveCustomerDemandLineItems(varRecId, selectedProducts);
    } else {
      return 'Error: Unsupported parent object type: ' + objName;
    }
  }

  private static String saveOpportunityLineItems(
    Id opportunityId,
    List<Object> selectedProducts
  ) {
    List<SObject> itemsToInsert = new List<SObject>();
    for (Object obj : selectedProducts) {
      Map<Object, Object> prod = (Map<Object, Object>) obj;
      String materialId = (String) prod.get('materialId');
      String materialNumber = (String) prod.get('materialNumber');
      String quantityStr = (String) prod.get('quantity');
      String priceStr = (String) prod.get('price');
      String quantityError = validateQuantity(quantityStr, materialNumber);
      if (quantityError != null) {
        return quantityError;
      }
      Integer quantity = parseQuantity(quantityStr);
      String priceError = validatePrice(priceStr, materialNumber);
      if (priceError != null) {
        return priceError;
      }
      Decimal price = parsePrice(priceStr);
      MD_OpportunityLineItem__c lineItem = new MD_OpportunityLineItem__c();
      lineItem.Name = materialNumber;
      lineItem.Product__c = materialId;
      lineItem.Opportunity__c = opportunityId;
      lineItem.Quantity__c = quantity;
      lineItem.Unit_Price__c = price;
      itemsToInsert.add(lineItem);
    }
    if (!itemsToInsert.isEmpty()) {
      insert itemsToInsert;
      return 'Selected products have been saved successfully.';
    }
    return 'No products to save.';
  }

  private static String saveQuoteLineItems(
    Id quoteId,
    List<Object> selectedProducts
  ) {
    List<SObject> itemsToInsert = new List<SObject>();
    for (Object obj : selectedProducts) {
      Map<Object, Object> prod = (Map<Object, Object>) obj;
      String materialId = (String) prod.get('materialId');
      String materialNumber = (String) prod.get('materialNumber');
      String quantityStr = (String) prod.get('quantity');
      String priceStr = (String) prod.get('price');
      String quantityError = validateQuantity(quantityStr, materialNumber);
      if (quantityError != null) {
        return quantityError;
      }
      Integer quantity = parseQuantity(quantityStr);
      String priceError = validatePrice(priceStr, materialNumber);
      if (priceError != null) {
        return priceError;
      }
      Decimal price = parsePrice(priceStr);
      MD_Quote_Line_Item__c lineItem = new MD_Quote_Line_Item__c();
      lineItem.Name = materialNumber;
      lineItem.Product2Id__c = materialId;
      lineItem.QuoteId__c = quoteId;
      lineItem.Quantity__c = quantity;
      lineItem.UnitPrice__c = price;
      itemsToInsert.add(lineItem);
    }
    if (!itemsToInsert.isEmpty()) {
      insert itemsToInsert;
      return 'Selected products have been saved successfully.';
    }
    return 'No products to save.';
  }

  private static String saveOrderLineItems(
    Id orderId,
    List<Object> selectedProducts
  ) {
    List<SObject> itemsToInsert = new List<SObject>();
    for (Object obj : selectedProducts) {
      Map<Object, Object> prod = (Map<Object, Object>) obj;
      String materialId = (String) prod.get('materialId');
      String materialNumber = (String) prod.get('materialNumber');
      String quantityStr = (String) prod.get('quantity');
      String priceStr = (String) prod.get('price');
      String quantityError = validateQuantity(quantityStr, materialNumber);
      if (quantityError != null) {
        return quantityError;
      }
      Integer quantity = parseQuantity(quantityStr);
      String priceError = validatePrice(priceStr, materialNumber);
      if (priceError != null) {
        return priceError;
      }
      Decimal price = parsePrice(priceStr);
      MD_OrderItem__c lineItem = new MD_OrderItem__c();
      lineItem.Product2Id__c = materialId;
      lineItem.OrderId__c = orderId;
      lineItem.Quantity__c = quantity;
      lineItem.Price__c = price;
      itemsToInsert.add(lineItem);
    }
    if (!itemsToInsert.isEmpty()) {
      insert itemsToInsert;
      return 'Selected products have been saved successfully.';
    }
    return 'No products to save.';
  }

  private static String saveCustomerDemandLineItems(
    Id demandId,
    List<Object> selectedProducts
  ) {
    List<SObject> itemsToInsert = new List<SObject>();
    for (Object obj : selectedProducts) {
      Map<Object, Object> prod = (Map<Object, Object>) obj;
      String materialId = (String) prod.get('materialId');
      String materialNumber = (String) prod.get('materialNumber');
      String quantityStr = (String) prod.get('quantity');
      String priceStr = (String) prod.get('price');
      String quantityError = validateQuantity(quantityStr, materialNumber);
      if (quantityError != null) {
        return quantityError;
      }
      Integer quantity = parseQuantity(quantityStr);
      String priceError = validatePrice(priceStr, materialNumber);
      if (priceError != null) {
        return priceError;
      }
      Decimal price = parsePrice(priceStr);

      Customer_Demand_Line_item__c lineItem = new Customer_Demand_Line_item__c();
      // lineItem.Name = materialNumber;
      lineItem.Material_Master__c = materialId;
      lineItem.Customer_Demand__c = demandId;
      lineItem.Quantity__c = quantity;
      lineItem.Amount__c = price;
      itemsToInsert.add(lineItem);
    }
    if (!itemsToInsert.isEmpty()) {
      insert itemsToInsert;
      return 'Selected products have been saved successfully.';
    }
    return 'No products to save.';
  }
  // Validate and parse quantity
  private static String validateQuantity(
    String quantityStr,
    String materialNumber
  ) {
    if (quantityStr != null && quantityStr != '') {
      if (!Pattern.matches('^-?\\d+$', quantityStr)) {
        return 'Error: Invalid quantity value for product ' +
          materialNumber +
          ': ' +
          quantityStr;
      }
    }
    return null;
  }

  private static Integer parseQuantity(String quantityStr) {
    if (quantityStr != null && quantityStr != '') {
      return Integer.valueOf(quantityStr);
    }
    return 0;
  }

  // Validate and parse price
  private static String validatePrice(String priceStr, String materialNumber) {
    if (priceStr != null && priceStr != '') {
      if (!Pattern.matches('^-?\\d+(\\.\\d+)?$', priceStr)) {
        return 'Error: Invalid price value for product ' +
          materialNumber +
          ': ' +
          priceStr;
      }
    }
    return null;
  }

  private static Decimal parsePrice(String priceStr) {
    if (priceStr != null && priceStr != '') {
      return Decimal.valueOf(priceStr);
    }
    return 0;
  }
}