force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Business Case</label>
    <nameField>
        <displayFormat>BCN-{000000000}</displayFormat>
        <label>Business Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Cases</relationshipLabel>
    <relationshipName>Business_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Agreement_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Date__c</fullName>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Account__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Machine_Installation__r.bill_to_account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Customer_Namea__c.field-meta.xml
<CustomField>
    <fullName>Customer_Namea__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>Machine_Installation__r.bill_to_account__r.SAP_Customer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Customer_Numbera__c.field-meta.xml
<CustomField>
    <fullName>Customer_Numbera__c</fullName>
    <label>Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Machine_Type__c.field-meta.xml
<CustomField>
    <fullName>Machine_Type__c</fullName>
    <formula>Machine_Name__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Machine Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Margin_Percent__c.field-meta.xml
<CustomField>
    <fullName>Margin_Percent__c</fullName>
    <description>Profit margin percentage on reagent sales</description>
    <label>Margin Percent</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Material_Descriptionsa__c.field-meta.xml
<CustomField>
    <fullName>Material_Descriptionsa__c</fullName>
    <label>Material Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Monthly_Reagent_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Reagent_Commitment__c</fullName>
    <label>Monthly Reagent Commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/SAP_Material_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Number__c</fullName>
    <formula>Machine_Name__r.Material_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Material Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Active 1</fullName>
            </value>
            <value>
                <fullName>Revised Quetta</fullName>
            </value>
            <value>
                <fullName>Active / Completed</fullName>
            </value>
            <value>
                <fullName>Active / Closed</fullName>
            </value>
            <value>
                <fullName>Closed Quetta</fullName>
            </value>
            <value>
                <fullName>Closed 1</fullName>
            </value>
            <value>
                <fullName>New Active</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Sum_of_Monthly_Reagent_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Monthly_Reagent_Commitment__c</fullName>
    <label>Sum of Monthly Reagent Commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Sum_of_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Unit_Cost__c</fullName>
    <label>Sum of Unit Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <label>Supplier Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AV - AlphaVenus</fullName>
            </value>
            <value>
                <fullName>A - Boule</fullName>
            </value>
            <value>
                <fullName>B - Boule</fullName>
            </value>
            <value>
                <fullName>DYM - Dymind</fullName>
            </value>
            <value>
                <fullName>ER - Erba</fullName>
            </value>
            <value>
                <fullName>RB - Erba</fullName>
            </value>
            <value>
                <fullName>HW - Headway</fullName>
            </value>
            <value>
                <fullName>NV - Nova</fullName>
            </value>
            <value>
                <fullName>OR - OCD</fullName>
            </value>
            <value>
                <fullName>STA - Stago</fullName>
            </value>
            <value>
                <fullName>CPART - VitalScientific</fullName>
            </value>
            <value>
                <fullName>D - VitalScientific</fullName>
            </value>
            <value>
                <fullName>E - VitalScientific</fullName>
            </value>
            <value>
                <fullName>LOC - VitalScientific</fullName>
            </value>
            <value>
                <fullName>DSERV - VitalScientific</fullName>
            </value>
            <value>
                <fullName>CSERV - VitalScientific</fullName>
            </value>
            <value>
                <fullName>PKG - VitalScientific</fullName>
            </value>
            <value>
                <fullName>INST - VitalScientific</fullName>
            </value>
            <value>
                <fullName>PART - VitalScientific</fullName>
            </value>
            <value>
                <fullName>DM - VitalScientific</fullName>
            </value>
            <value>
                <fullName>U - VitalScientific</fullName>
            </value>
            <value>
                <fullName>S - VitalScientific</fullName>
            </value>
            <value>
                <fullName>F - VitalScientific</fullName>
            </value>
            <value>
                <fullName>YHLO - YHLO</fullName>
            </value>
            <value>
                <fullName>ZYB - ZYBIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XRAY - Xray</fullName>
            </value>
            <value>
                <fullName>HM - Heamatology</fullName>
            </value>
            <value>
                <fullName>COAG - Coagulation</fullName>
            </value>
            <value>
                <fullName>ELCT - Electrolyte</fullName>
            </value>
            <value>
                <fullName>URIN - Urine</fullName>
            </value>
            <value>
                <fullName>UBT - Urea Breath Test</fullName>
            </value>
            <value>
                <fullName>ABG - Arterial Blood Gas</fullName>
            </value>
            <value>
                <fullName>POC - Point of Care</fullName>
            </value>
            <value>
                <fullName>IMA - Immunoassay</fullName>
            </value>
            <value>
                <fullName>CC - Clinical Chemistry</fullName>
            </value>
            <value>
                <fullName>ELT - Electrolyte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Machine_Installation__c/Machine_Installation__c.object-meta.xml
<CustomObject>
    <label>Machine Installation</label>
    <nameField>
        <displayFormat>DMI-{000000}</displayFormat>
        <label>Machine Installation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Installations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Machine_Installation__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <formula>Diagnostic_Machine__r.Material_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Machine_Installation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Assessment</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Invoiced/Sold</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Asset</fullName>
                <isActive>false</isActive>
                <label>Pending Asset</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MD_Asset__c/MD_Asset__c.object-meta.xml
<CustomObject>
    <label>Diagnostic Machine</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Diagnostic Machine Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnostic Machines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MD_Asset__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <formula>Product__r.Material_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MD_Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MD_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Asset</fullName>
            </value>
            <value>
                <fullName>Initial Assessment</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Invoiced/Sold</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Demo Failed</fullName>
                <isActive>false</isActive>
                <label>Demo Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MD_Asset__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <formula>text ( Product__r.Technology__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technology</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BusinessCaseMasterSnapshotBatch.cls
public class BusinessCaseMasterSnapshotBatch implements Database.Batchable<SObject>, Database.Stateful {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Return all active business cases to process
        return Database.getQueryLocator([
             SELECT Id, Name, Customer_Namea__c,Agreement_Date__c,Sum_of_Monthly_Reagent_Commitment__c, Customer_Numbera__c, Sum_of_Unit_Cost__c,
                Material_Number__c, Material_Descriptionsa__c,Status__c,Quantity__c,Margin_Percent__c,
                (
                    SELECT  Id,
                            Name,
                            Status__c,
                            Account__c,
                            Account__r.Province__c,
                            Account__r.City__c,
                            Account__r.AddressLine_1__c,
                            Account__r.Addess_Line_2__c,
                            Account__r.Postal_Code__c,
                            Account__r.Country_Code__c,
                            Customer_Number__c,
                            Customer_Name__c,
                            Supplier_Name__c,
                            Technology__c,
                            Region__c,
                            SAP_Material_Number__c,
                            Machine_Type__c,
                            Quantity__c,
                            Monthly_Reagent_Commitment__c,
                            Unit_Cost__c,
                            Margin_Percent__c,
                            Agreement_Date__c,
                            Asset_Number__c,
                            Asset_Number__r.Status__c,
                            Machine_Installation__r.Ship_To_Account__c,
                            Machine_Installation__r.Ship_To_Account__r.SAP_Customer_Number__c,
                            Machine_Installation__r.Ship_To_Account__r.Name,
                            Machine_Installation__r.Ship_To_Account__r.Province__c,
                            Machine_Installation__r.Ship_To_Account__r.City__c,
                            Machine_Installation__r.Ship_To_Account__r.AddressLine_1__c,
                            Machine_Installation__r.Ship_To_Account__r.Addess_Line_2__c,
                            Machine_Installation__r.Ship_To_Account__r.Postal_Code__c,
                            Machine_Installation__r.Ship_To_Account__r.Country_Code__c,
                            Machine_Installation__r.Diagnostic_Machine__r.Vendor__c,
                            Machine_Installation__r.Diagnostic_Machine__r.Technology__c,
                            Ship_To_Customer_Number__c,
                            Ship_To_Customer_Name__c,
                            Machine_Installation__r.SAP_Account_No_Bill_To__c,
                            Machine_Installation__r.bill_to_account__r.Name,
                            Machine_Installation__r.Material_Number__c,
                            Machine_Installation__r.Status__c,
                            Machine_Installation__r.bill_to_account__r.Province__c,
                            Machine_Installation__r.bill_to_account__r.City__c,
                            Machine_Installation__r.bill_to_account__r.AddressLine_1__c,
                            Machine_Installation__r.bill_to_account__r.Postal_Code__c,
                            Machine_Installation__r.bill_to_account__r.Country_Code__c
                    FROM Business_Cases__r 
                    WHERE RecordType.Name = 'Individual Business Case' and (Status__c like '%Active%' or Status__c like '%Revised%' or Status__c like '%New%')
                   // LIMIT 1
                )
            FROM Business_Case__c
            WHERE RecordType.Name = 'Master Business Case'
            
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Business_Case__c> scope) {
        System.debug('📦 Executing batch of size: ' + scope.size());
        
        // Call your existing logic for processing one batch
        Integer snapshotsCreated = BusinessCaseSnapshotService.processMasterBatchSnapshots(scope);
        System.debug(' Batch created ' + snapshotsCreated + ' snapshots');
    }

    public void finish(Database.BatchableContext bc) {
        System.debug(' All batches complete.');
    }
}